query GetCharacter($characterId: ID!) {
  character(id: $characterId) {
    ...CharacterInfo
  }
}

query GetClass($classId: ID!) {
  class(id: $classId) {
    ...ClassInfo
  }
}

query GetGameMeta($gameId: ID!) {
  game(id: $gameId) {
    ...GameMetaInfo
  }
}

query GetItem($itemId: ID!) {
  item(id: $itemId) {
    ...ItemInfo
  }
}
